### ISSUE TITLE
Bottom of FFMPEG screen recording is being left out

### ISSUE THREAD

**Issue by gmierz** [sitespeedio/browsertime#1446] opened 2020-12-01 16:45 UTC
The changes in PR #1435 fixed the majority of the issues I was seeing when using FFMPEG for screen recording but it seems like the bottom of the videos is being left out when using FFMPEG in comparison the the Firefox Window Recorder. See below for a video of the difference (before is the window recording, after is the FFMPEG recorder).

Video: https://mozilla.modular.im/_matrix/media/r0/download/mozilla.org/f22e1eaed505f38b6274733b5726a2b42a5bc229

**Comment by soulgalore** [comment] 2020-12-01 21:37
Hi @gmierz let me test it tomorrow. I always test with the HAR Export trigger and devtools open (to be able to get the HAR file) so my guess is that I've made it default to skip that part of the screen (it looks to big though the part that its missed, but maybe its a combination of that + the extra pixels added at the top).

**Comment by soulgalore** [comment] 2020-12-02 01:55
Hi again @gmierz I 'm having a hard time to reproduce it, can you show me what viewport you are using? I tried with the default settings only Mac and there it looks to have the full screen. Tried in Docker and it looks like this:
<img width="1359" alt="Screenshot 2020-12-02 at 02 49 39" src="https://user-images.githubusercontent.com/540757/100818090-b5115100-3449-11eb-986e-c495a1fd1a14.png">
And without the HAR enabled it catches those last parts too.

**Comment by gmierz** [comment] 2020-12-03 14:52
Hmm interesting, we are using a 1024x768 as the viewport. Locally, I tried using 1920x1080 and it was also breaking. Here's the browsertime command line if it helps:
`node /Users/cltbld/tasks/task_1605816725/fetches/browsertime/node_modules/browsertime/bin/browsertime.js --firefox.geckodriverPath /Users/cltbld/tasks/task_1605816725/fetches/geckodriver /Users/cltbld/tasks/task_1605816725/build/tests/raptor/raptor/browsertime/../../browsertime/browsertime_pageload.js --viewPort 1024x768 --browser firefox --firefox.binaryPath /Users/cltbld/tasks/task_1605816725/build/application/Firefox Nightly.app/Contents/MacOS/firefox --browsertime.page_cycles 2 --browsertime.url https://docs.google.com/spreadsheets/d/1jT9qfZFAeqNoOK97gruc34Zb7y_Q-O_drZ8kSXT-4D4/edit?usp=sharing --browsertime.page_cycle_delay 1000 --browsertime.post_startup_delay 30000 --firefox.profileTemplate /var/folders/2w/4fyf6nwx0bn58rfry149c2y8000017/T/tmpMCqj85.mozrunner --skipHar --pageLoadStrategy none --webdriverPageload true --firefox.disableBrowsertimeExtension true --pageCompleteCheckStartWait 5000 --pageCompleteCheckPollTimeout 1000 --timeouts.pageLoad 60000 --timeouts.script 120000 --resultDir /Users/cltbld/tasks/task_1605816725/build/blobber_upload_dir/browsertime-results/google-sheets --video true --visualMetrics false --firefox.windowRecorder false --xvfbParams.display 0 -n 25`

And here's our pageload script: https://searchfox.org/mozilla-central/source/testing/raptor/browsertime/browsertime_pageload.js

**Comment by soulgalore** [comment] 2020-12-03 20:50
Let me compare tomorrow and also run with windowRecorder and compare them. On your local machine, do you use Mac/Linux or Windows? Wanna try to reproduce.

**Comment by soulgalore** [comment] 2020-12-04 07:40
I'm testing on my Mac and cannot see any difference there but we have a little bit different logic for ffmpeg for Apple, Linux and Windows. 

I tried with our Docker container (I don't have Linux installed at the moment) using Ubuntu:
`docker run --rm -v "$(pwd)":/browsertime sitespeedio/browsertime "https://docs.google.com/spreadsheets/d/1jT9qfZFAeqNoOK97gruc34Zb7y_Q-O_drZ8kSXT-4D4/edit?usp=sharing" -n 1 -b firefox --video --skipHar --viewPort 1024x768`

Running FFMPEG looks like this for me:
<img width="1024" alt="Screenshot 2020-12-04 at 08 34 52" src="https://user-images.githubusercontent.com/540757/101135117-a70b2e00-360b-11eb-80a5-6c469363b927.png">

And using windowRecorder (`docker run --rm -v "$(pwd)":/browsertime sitespeedio/browsertime "https://docs.google.com/spreadsheets/d/1jT9qfZFAeqNoOK97gruc34Zb7y_Q-O_drZ8kSXT-4D4/edit?usp=sharing" -n 1 -b firefox --video --skipHar --viewPort 1024x768 --firefox.windowRecorder`):
<img width="1021" alt="Screenshot 2020-12-04 at 08 37 03" src="https://user-images.githubusercontent.com/540757/101135301-eafe3300-360b-11eb-9057-b16b5f424bea.png">

It looks like we miss a couple of pixels but I cannot see the same things as you @gmierz .

I can install Linux and maybe windows to try out but first I need your OS details so I'm sure I'm using the same as you.

**Comment by gmierz** [comment] 2020-12-04 14:13
This is good to know, thanks for checking @soulgalore! I have a feeling it has something to do with the hardware we're running on - I'll continue debugging this. We use Mac Minis for the MacOS tests, and HP Moonshots for the linux and windows tests:
```
HPE Moonshot 1500 System (45 cartridges per 4.3U)
1500W Hot Plug redundant (1+1) Power Supply
45 m710x ProLiant cartridges
  1 Intel E3-1585L v5 3.0GHz CPU (4 cores)
  8GB DDR4 2400MHz RAM
  1 256GB PCIe M.2 2280 SSD
  1 64GB SATA M.2 2242 SSD
  1 Intel Iris Pro Graphics P580
```

```
Model Name: Mac Mini
Model Identifier: Macmini7,1
Processor Name: Intel Core i7 (I7-4578U?)
Processor Speed: 3 GHz
Number of Processors: 1
Total Number of Cores: 2
GPU: Intel Iris Graphics 5100
L2 Cache (per Core): 256 KB
L3 Cache: 4 MB
Memory: 16 GB
Disk: SSD 251 GB (251,000,193,024 bytes)
```

**Comment by soulgalore** [comment] 2021-04-12 12:22
I'm closing this, but please re-open if you still have an issue with it!

**Closed by soulgalore** 2021-04-12 12:22 UTC
