### ISSUE TITLE
Unexplained jump in SpeedIndex/etc values after updating browsertime

### ISSUE THREAD

**Issue by jesup** [sitespeedio/browsertime#1632] opened 2021-09-08 17:46 UTC
Old browsertime version: 11.0.2
New browsertime version: 14.0.3

Metrics measured in the Mozilla AreWeFastYet.com site jumped when we landed browsertime 14.0.3 (and an update to ImageMagik).   Paypal, Google Docs, Ebay, Youtube; also (lesser changes) office, instagram, reddit, bing and a few others.   Seen on multiple platforms (linux, mac, windows). 

Measured against recordings replayed with mitmdump; recordings can be downloaded via tooltool.

FCP and FVC don't show any noticeable changes.   LVC shows clear changes in the same sites as above.

Original performance alert: https://bugzilla.mozilla.org/show_bug.cgi?id=1728776

Example from ebay.   The bump a few days before the final change was a landing of the browsertime change that was backed out.
https://treeherder.mozilla.org/perfherder/graphs?highlightAlerts=1&highlightChangelogData=1&series=autoland,3382404,1,13&timerange=1209600&zoom=1629910141353,1631125201572,2156.5555555555557,4510.444444444444

We select the area for comparison with --viewport (and --orange).

**Comment by jmaher** [comment] 2021-09-08 18:23
a bit more context, we had originally upgraded August 27th and had to revert our change August 28th due to other failures.  Then we upgraded again on August 31st.  You can see in the graph linked above for ebay the changes match this time frame for a regression, improvement, and regression again.  We have also run the tests again before/after the change on the 31st to ensure we can repeat this regression and that holds true.

**Comment by soulgalore** [comment] 2021-09-08 18:47
Thanks for all the info, that is really helpful. I'll try to reproduce it ASAP. I cannot see anything in the changelog on the Browsertime side that rings any bells so I need to dig into different versions. What Firefox version are you using, I'll try with latest stable.

**Comment by soulgalore** [comment] 2021-09-08 18:53
@jesup is Geckoprofiler turned on when you run your tests? One change that was introduced was some extra wait time for Geckorpofiler to settle see https://github.com/sitespeedio/browsertime/issues/1538. Just looking for changes that somehow can affect Firefox.

**Comment by soulgalore** [comment] 2021-09-08 18:55
To run that as before the change you can add `--firefox.geckoProfilerSettleTime 0`

**Comment by soulgalore** [comment] 2021-09-09 07:06
Ok, I found what changed. it was actually in the [changed section in the CHANGELOG](https://github.com/sitespeedio/browsertime/blob/main/CHANGELOG.md#1200---2021-04-15) but I missed it when I browsed it. The default wait time before the page complete check changed to be 8 seconds instead of 5 (see https://github.com/sitespeedio/browsertime/pull/1542). You can revert that change when you run with a configuration: `--pageCompleteWaitTime 5000` and it will be the same as before. The reason I changed it was that running the iPhone emulator on a Mac M1 was shaky with the shorter wait time (the tests ended before it has started). Since the values change on some pages, it means that the visual continues to change in the page if you extend your testing time.

If someone else needs to debug the same thing in the future this is what I did:
1. I created a new large instance on Digital Ocean (CPU optimized $80) to have a new instance to run the tests. DO isn't optimal but since the change you've seen was so large I was thinking I would be able to reproduce it there,
2. I followed the instructions on https://www.sitespeed.io/documentation/sitespeed.io/installation/#linux but instead on installing sitespeed.io I installed browsertime.
3. I started with the two different versions you provided: `npm install browsertime@14.0.3 -g` and then run eleven runs testing eBay: `browsertime --xvfb --visualMetrics https://www.ebay.com -n 11 -b firefox --skipHar`
4. Then installed the old version: `npm install browsertime@11.0.2 -g` and runner the test again and I could see that I got a difference in Speed Index.
5. Then I started to try other releases in between and reading the changelog again. After some time and testing I found the the pageCompleteChange and then installed 14.0.3 again and added the extra config: `browsertime --xvfb --visualMetrics https://www.ebay.com -n 11 -b firefox --skipHar --pageCompleteWaitTime 5000 ` and verified that the metrics is ok.


So if I'm right you should add `--pageCompleteWaitTime 5000`  and SpeedIndex should be the same. However it's also the question on when to end the tests, that is harder on page that continues to change. 

Lets keep the issue open until you have been able to verify that it works.

**Comment by jmaher** [comment] 2021-09-09 17:06
I didn't verify every single change we saw, but adding
`--pageCompleteWaittime 5000` has reset the results back for all of our
linux tests.  I even retriggered the tests and the data is repeatable.

As for our needs at Mozilla- we need to decide if we want to accept this
change or add the cli flag to reset it back to 5000ms.

I believe you can close this issue.

**Closed** 2021-09-09 19:11 UTC
