### ISSUE TITLE
browsertime complaining about 'urlOrAlias.startsWith is not a function'

### ISSUE THREAD

**Issue by Myvryn** [sitespeedio/browsertime#1206] opened 2020-02-20 23:07 UTC
I'm seeing a strange issue with browsertime navigating to a page that redirects to a page with a # in the url. I am, at this point assuming that the problem lies with the "redrawn url" as the test will work fine if I substitute the URL with something different.

### Code
``` javascript
module.export = async function(context, command){
    await command.measure.start(
       'http://signin.test.myco.com/CustomerPortal/Administration,
        'Open Management Page');
}
```
This redirects to the following URL: https://signin.test.myco.com/CustomerPortal/Administration#/internal/customers

### Command

```
docker run --privileged --shm-size=1g --rm -v "%CD%":/sitespeed.io sitespeedio/sitespeed.io LoadManagementPage.js --multi -b chrome -n 1 --preScript login_prescript.js --debug

(note:  the login_prescript.js works fine)
```

### The Error
```
ERROR: [browsertime] TypeError: urlOrAlias.startsWith is not a function
    at Measure.start (/usr/src/app/node_modules/browsertime/lib/core/engine/command/measure.js:140:19)
    at /usr/src/app/node_modules/browsertime/lib/core/engine/run.js:9:32
    at Iteration.run (/usr/src/app/node_modules/browsertime/lib/core/engine/iteration.js:179:15)
    at async Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:121:20)
    at async Object.analyzeUrl (/usr/src/app/lib/plugins/browsertime/analyzer.js:118:21)
    at async Object.processMessage (/usr/src/app/lib/plugins/browsertime/index.js:134:24)
```

**Comment by Myvryn** [comment] 2020-02-20 23:38
BTW:  I get the same error running via:
### NPX COMMAND
`npx sitespeed.io LoadManagementPage.js --multi -n 1 --preScript login_prescript.js`

**Comment by soulgalore** [comment] 2020-02-21 07:24
Hi @Myvryn thanks for filing the issue, yeah it looks like a bug, let me see how I can reproduce it.

**Comment by soulgalore** [comment] 2020-02-21 07:27
I did a quick test just for https://bit.ly/32kbmVl -> https://www.sitespeed.io/#test but that didn't fail. Any idea how I easiest could reproduce the problem?

**Comment by Myvryn** [comment] 2020-02-21 14:43
My first thought would be to try to do the pattern like so...

Directory#/directory/directory

Rather than directory/#keyword

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Myvryn** [comment] 2020-02-21 16:29
Oh my word...  :P  Figured it out. When I went to reproduce this, EVERY url I had was producing the same error.

Looking at the code, I had module.export rather than module.exports  <-- missing an 's'

uggg...

**Comment by soulgalore** [comment] 2020-02-21 18:11
Np @Myvryn similar things has happened to me too :) Can we close the issue then?

**Comment by Myvryn** [comment] 2020-02-21 23:33
Definitely

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Closed** 2020-02-23 11:11 UTC
Labels: bug
