### ISSUE TITLE
ERROR: Error running browsertime Error: Unhandled value type undefined found when adding data

### ISSUE THREAD

**Issue by phongiswindy** [sitespeedio/browsertime#979] opened 2019-10-30 18:34 UTC
I encountered this `ERROR: Error running browsertime Error: Unhandled value type undefined found when adding data` when testing certain domains such as `https://conso.jp`, `http://www.reallygoodmusic.com`, `http://aquaphoenix.com`, etc. The detail error is as follow:

```
Google Chrome 77.0.3865.75 
Mozilla Firefox 69.0
[2019-10-30 18:30:45] INFO: Running tests using Chrome - 3 iteration(s)
[2019-10-30 18:30:45] INFO: Testing url http://www.reallygoodmusic.com iteration 1
[2019-10-30 18:30:56] ERROR: Error running browsertime Error: Unhandled value type undefined found when adding data
    at addRecursive (/usr/src/app/lib/support/statistics.js:106:17)
    at Object.keys.forEach.key (/usr/src/app/lib/support/statistics.js:87:15)
    at Array.forEach (<anonymous>)
    at addRecursive (/usr/src/app/lib/support/statistics.js:85:32)
    at Object.keys.forEach.key (/usr/src/app/lib/support/statistics.js:87:15)
    at Array.forEach (<anonymous>)
    at addRecursive (/usr/src/app/lib/support/statistics.js:85:32)
    at Object.keys.forEach.key (/usr/src/app/lib/support/statistics.js:87:15)
    at Array.forEach (<anonymous>)
    at addRecursive (/usr/src/app/lib/support/statistics.js:85:32)
    at Object.keys.forEach.key (/usr/src/app/lib/support/statistics.js:87:15)
    at Array.forEach (<anonymous>)
    at addRecursive (/usr/src/app/lib/support/statistics.js:85:32)
    at Statistics.addDeep (/usr/src/app/lib/support/statistics.js:112:5)
    at Collector.perIteration (/usr/src/app/lib/core/engine/collector.js:127:20)
    at Engine.runByScript (/usr/src/app/lib/core/engine/index.js:127:25)
```

**Comment by soulgalore** [comment] 2019-10-30 19:49
Hi @phongiswindy thanks for the bug report! I could reproduce (thanks a lot for sharing the URL, that make things so much easier to debug). I'll try to fix it before I do the next release this weekend.

Best
Peter

**Comment by soulgalore** [comment] 2019-10-30 20:23
The problem is that we missed that the document.title can be anything else than a string, On those sites it's an image! Fix coming up.

**Comment by phongiswindy** [comment] 2019-10-30 20:48
Thank you so much for your dedicated support to the project! <3

**Comment by soulgalore** [comment] 2019-10-30 20:59
This is fixed in master and going out in a stable release on Friday or Saturday.

**Comment by phongiswindy** [comment] 2019-11-03 05:41
Hi @soulgalore, I think 7.0.0 could solve the problem for all of the links I mentioned above. However, I found that this error again for `http://theway.org.uk` on both Chrome and Firefox. So I am not sure if there's any else can be fixed. The link could be loaded normally in browser.

docker run --rm -v "$(pwd)":/browsertime sitespeedio/browsertime:7.0.0 --browser firefox http://theway.org.uk
Google Chrome 78.0.3904.87 
Mozilla Firefox 70.0
[2019-11-03 05:38:08] INFO: Running tests using Firefox - 3 iteration(s)
[2019-11-03 05:38:11] INFO: Testing url http://theway.org.uk iteration 1
[2019-11-03 05:38:20] INFO: Waiting on har-export-trigger to collect the HAR
[2019-11-03 05:38:27] ERROR: Error running browsertime Error: Unhandled value type function found when adding data
    at addRecursive (/usr/src/app/lib/support/statistics.js:106:17)
    at /usr/src/app/lib/support/statistics.js:87:15
    at Array.forEach (<anonymous>)
    at addRecursive (/usr/src/app/lib/support/statistics.js:85:32)
    at /usr/src/app/lib/support/statistics.js:87:15
    at Array.forEach (<anonymous>)
    at addRecursive (/usr/src/app/lib/support/statistics.js:85:32)
    at /usr/src/app/lib/support/statistics.js:87:15
    at Array.forEach (<anonymous>)
    at addRecursive (/usr/src/app/lib/support/statistics.js:85:32)
    at /usr/src/app/lib/support/statistics.js:87:15
    at Array.forEach (<anonymous>)
    at addRecursive (/usr/src/app/lib/support/statistics.js:85:32)
    at Statistics.addDeep (/usr/src/app/lib/support/statistics.js:112:5)
    at Collector.perIteration (/usr/src/app/lib/core/engine/collector.js:127:20)
    at Engine.runByScript (/usr/src/app/lib/core/engine/index.js:125:25)

**Comment by soulgalore** [comment] 2019-11-17 11:44
Ah sorry I missed that. That page is overriding document.URL, let me fix that to the next release.

**Comment by soulgalore** [comment] 2020-04-13 11:23
The fix has been release, please report back if its still an issue.

**Closed by soulgalore** 2020-04-13 11:23 UTC
Labels: bug
